### ISSUE TITLE
The funding files are not filtered for the list of coutnries

### ISSUE THREAD

**Issue by MikaelaSmitGlobalFund** [globalfund-pri/model_code_pipeline#38]
https://github.com/globalfund-pri/model_code_pipeline/blob/9adc65b68e9ff5c8677027b9d087d79ef4677bcf/src/tgftools/approach_b.py#L234

@tbhallett, I rerun IC8 with only SSA countries for malaria. The reason for that being that the strategy targets were based on malaria simulation for SSA only. When I updated the list of modelled countries it threw an error at this line, because the total funding (the file contained all countries) seemed to not be filtered by the list of countries. Could we add a filter so we can limit the comparison? At this stage I am having to create new files and remove rows of non-SSA countries, which seems error prone. 

Happy to have a first stab at editing the code but also concious that this is a tgftool file.

**Comment by tbhallett** [comment]
This is now fixed.
